# Main colors
background            #f6fafe
foreground            #181c20
cursor                #181c20
cursor_text_color     #f6fafe
selection_background  #d2e5f5
selection_foreground  #0b1d29
url_color             #62597c

# ANSI colors
color0                #f6fafe
color1                #ba1a1a
color2                #62597c
color3                #4f616e
color4                #216487
color5                #ccc1e9
color6                #b6c9d8
color7                #181c20
color8                #dde3ea
color9                #ffdad6
color10               #e8ddff
color11               #d2e5f5
color12               #c7e7ff
color13               #374955
color14               #4a4263
color15               #41484d

# Starship prompt bubbles
color255              #c7e7ff
color254              #216487
color253              #d2e5f5
color252              #4f616e
color251              #e8ddff
color250              #62597c
color249              #ffdad6
color248              #ba1a1a
color232              #001e2e
color233              #ffffff
color234              #0b1d29
color235              #ffffff
color236              #1e1635
color237              #ffffff
color238              #410002
color239              #ffffff
color240              #001e2e
color243              #216487
color244              #ba1a1a
color245              #c1c7ce

# UI elements
active_tab_foreground   #ffffff
active_tab_background   #216487
inactive_tab_foreground #001e2e
inactive_tab_background #c7e7ff
active_border_color     #216487
inactive_border_color   #71787e

# Marks
mark1_foreground        #001e2e
mark1_background        #c7e7ff
mark2_foreground        #0b1d29
mark2_background        #d2e5f5
mark3_foreground        #1e1635
mark3_background        #e8ddff
